### ISSUE TITLE
[666896] synergy: Segfaults when moving over to host screen with cursor when clipboard is synced

### ISSUE THREAD

**Issue by epakai** [epakai/synergy-debian#34]

**Comment by epakai** [comment]
BTS_msg_id: <20120402100326.644.69143.reportbug@ws042498-linux.oce.nl>
BTS author: Manuel Bilderbeek <bilm@oce.nl>

Package: synergy
Version: 1.3.8-1
Severity: important

Dear Maintainer,
   * What led up to the situation?

For some reason, synergy started crashing after updating my system to
the latest testing state of affairs when I move the cursor to the
'other' system. Looking at the backtrace, it has to do with the
clipboard.

* What exactly did you do (or not do) that was effective (or
     ineffective)?

The whole app is becoming almost useless, as I can't find a workaround.

   * What was the outcome of this action?

Crash.

   * What outcome did you expect instead?

No crash :P

This is what I could catch with gdb:

(gdb) bt
#0  __pthread_mutex_lock (mutex=0x0) at pthread_mutex_lock.c:50
#1  0x0811e15f in CArchMultithreadPosix::lockMutex(CArchMutexImpl*) ()
#2  0x0811be4d in CArch::lockMutex(CArchMutexImpl*) ()
#3  0x0811cfcc in IArchString::convStringMBToWC(wchar_t*, char const*, unsigned int, bool*) ()
#4  0x0811c7a8 in CArch::convStringMBToWC(wchar_t*, char const*, unsigned int, bool*) ()
#5  0x081a16dd in CUnicode::textToUTF8(std::string const&, bool*) ()
#6  0x08150896 in CXWindowsClipboardTextConverter::toIClipboard(std::string const&) const ()
#7  0x08148988 in CXWindowsClipboard::icccmFillCache() ()
#8  0x08148695 in CXWindowsClipboard::doFillCache() ()
#9  0x0814866a in CXWindowsClipboard::fillCache() const ()
#10 0x081482ca in CXWindowsClipboard::has(IClipboard::EFormat) const ()
#11 0x0819f71d in IClipboard::copy(IClipboard*, IClipboard const*, unsigned int) ()
#12 0x08139abc in CXWindowsScreen::getClipboard(unsigned char, IClipboard*) const ()
#13 0x0819eb44 in CScreen::getClipboard(unsigned char, IClipboard*) const ()
#14 0x0817743e in CPrimaryClient::getClipboard(unsigned char, IClipboard*) const ()
#15 0x0817cbb2 in CServer::onClipboardChanged(CBaseClientProxy*, unsigned char, unsigned int) ()
---Type <return> to continue, or q <return> to quit---
#16 0x08179b59 in CServer::switchScreen(CBaseClientProxy*, int, int, bool) ()
#17 0x0817d8a2 in CServer::onMouseMovePrimary(int, int) ()
#18 0x0817c474 in CServer::handleMotionPrimaryEvent(CEvent const&, void*) ()
#19 0x08182721 in TMethodEventJob<CServer>::run(CEvent const&) ()
#20 0x08123027 in CEventQueue::dispatchEvent(CEvent const&) ()
#21 0x08118748 in ?? ()
#22 0x0811893b in ?? ()
#23 0x0811d4a9 in CArchDaemonUnix::daemonize(char const*, int (*)(int, char const**)) ()
#24 0x0811bab2 in CArch::daemonize(char const*, int (*)(int, char const**)) ()
#25 0x081189b2 in ?? ()
#26 0x08118a94 in ?? ()
#27 0x08119cc9 in main ()


-- System Information:
Debian Release: wheezy/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'stable')
Architecture: i386 (i686)

Kernel: Linux 3.2.0-2-686-pae (SMP w/2 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

Versions of packages synergy depends on:
ii  libc6         2.13-27
ii  libgcc1       1:4.6.3-1
ii  libice6       2:1.0.7-2
ii  libsm6        2:1.2.0-2
ii  libstdc++6    4.6.3-1
ii  libx11-6      2:1.4.4-4
ii  libxext6      2:1.3.0-3
ii  libxi6        2:1.4.5-1
ii  libxinerama1  2:1.1.1-3
ii  libxtst6      2:1.2.0-4

synergy recommends no packages.

synergy suggests no packages.

-- no debconf information

This message and attachment(s) are intended solely for use by the addressee and may contain information that is privileged, confidential or otherwise exempt from disclosure under applicable law.

If you are not the intended recipient or agent thereof responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.

If you have received this communication in error, please notify the sender immediately by telephone and with a 'reply' message.

Thank you for your co-operation.

**Comment by epakai** [comment]
BTS_msg_id: <E1SnsmI-0000E6-OW@franck.debian.org>
BTS author: Jeff Licquia <licquia@debian.org>

Source: synergy
Source-Version: 1.3.8-2

We believe that the bug you reported is fixed in the latest version of
synergy, which is due to be installed in the Debian FTP archive.

A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 666896@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Jeff Licquia <licquia@debian.org> (supplier of updated synergy package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.8
Date: Sat, 07 Jul 2012 15:08:33 -0400
Source: synergy
Binary: synergy
Architecture: source amd64
Version: 1.3.8-2
Distribution: unstable
Urgency: low
Maintainer: Jeff Licquia <licquia@debian.org>
Changed-By: Jeff Licquia <licquia@debian.org>
Description: 
 synergy    - Share mouse, keyboard and clipboard over the network
Closes: 666896
Changes: 
 synergy (1.3.8-2) unstable; urgency=low
 .
   * Build with dpkg-buildflags hardening support.
   * Update Standards-Version.
   * Apply mutex initialization fix from upstream.  This seems
     to fix a number of segfault issues.  Closes: #666896.
Checksums-Sha1: 
 c75056484188f7c21c0ce37260c79e434a3279d8 1225 synergy_1.3.8-2.dsc
 86ad8df35327ea1a1233939cd101edcc22479e70 17209 synergy_1.3.8-2.debian.tar.gz
 741b367de092ea6df9be622341a691de421ba606 601966 synergy_1.3.8-2_amd64.deb
Checksums-Sha256: 
 6f88ea1707583351e33ceaf40f42c683a4ace321d1ee8bc6d67f7e3fc91b28d4 1225 synergy_1.3.8-2.dsc
 350e1ed6378f71e4fd1acbb476c7a7664a55c8bbde2ca473f5671c980e422515 17209 synergy_1.3.8-2.debian.tar.gz
 ea6655810d2a80252b64910a649e6c70f5588ca7e5317c3aeddea273a75473d5 601966 synergy_1.3.8-2_amd64.deb
Files: 
 a8bd92855c2e89944a71084838f8c912 1225 x11 optional synergy_1.3.8-2.dsc
 1fac5c9128d22003b7ca94977d7ee318 17209 x11 optional synergy_1.3.8-2.debian.tar.gz
 1fec13fdd4ca5240f15f0d3e3884b3ab 601966 x11 optional synergy_1.3.8-2_amd64.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iEYEARECAAYFAk/5lLMACgkQYApVP/ZmyR29ugCeMEoHWPzDuVD77eFwsCp05dgX
MjIAnRUIan/OChkMOCYg0LeBlOf9B6PP
=81I2
-----END PGP SIGNATURE-----

**Comment by epakai** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A long time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
