### ISSUE TITLE
[664217] synergy: crash when pasting client clipboard into Google Chrome

### ISSUE THREAD

**Issue by epakai** [epakai/synergy-debian#70]

**Comment by epakai** [comment]
BTS_msg_id: <20120316184908.GA1034@pimlott.net>
BTS author: Andrew Pimlott <andrew@pimlott.net>

Package: synergy
Version: 1.3.8-1
Severity: normal

Dear Maintainer,

I can reproducibly crash my local synergys by copying text on the
synergy client host, then trying to paste it into the Google Chrome URL
bar by middle-clicking.  When I run 

    synergys --address 127.0.0.1 --no-daemon

under gdb, I get the following stack trace:

    Program received signal SIGSEGV, Segmentation fault.
    0xb7fbe18d in pthread_mutex_lock ()
       from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
    (gdb) where
    #0  0xb7fbe18d in pthread_mutex_lock ()
       from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
    #1  0x0811e15f in CArchMultithreadPosix::lockMutex(CArchMutexImpl*) ()
    #2  0x0811be4d in CArch::lockMutex(CArchMutexImpl*) ()
    #3  0x0811ce6e in IArchString::convStringWCToMB(char*, wchar_t const*, unsigned int, bool*) ()
    #4  0x0811c7ec in CArch::convStringWCToMB(char*, wchar_t const*, unsigned int, bool*) ()
    #5  0x081a1469 in CUnicode::UTF8ToText(std::string const&, bool*) ()
    #6  0x0815086c in CXWindowsClipboardTextConverter::fromIClipboard(std::string const&) const ()
    #7  0x08147a7f in CXWindowsClipboard::addSimpleRequest(unsigned long, unsigned long, unsigned long, unsigned long) ()
    #8  0x08147896 in CXWindowsClipboard::addRequest(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) ()
    #9  0x0813ba01 in CXWindowsScreen::handleSystemEvent(CEvent const&, void*) ()
    #10 0x08142dbf in TMethodEventJob<CXWindowsScreen>::run(CEvent const&) ()
    #11 0x08123027 in CEventQueue::dispatchEvent(CEvent const&) ()
    #12 0x08118748 in ?? ()
    #13 0x081189b9 in ?? ()
    #14 0x08118a94 in ?? ()
    #15 0x08119cc9 in main ()

There are no log messages from synergys immediatly before the crash.

My synergyc is Debian version 1.3.1-5 from squeeze.  It is tunnelled
over ssh.

Pasting into other applications, for example an xterm, works fine.  It
is only pasting into Chrome that breaks.  And of course, pasting into
Chrome from a local selection works.

Andrew

-- System Information:
Debian Release: wheezy/sid
  APT prefers unstable
  APT policy: (500, 'unstable')
Architecture: i386 (i686)

Kernel: Linux 3.2.0-1-486
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/bash

Versions of packages synergy depends on:
ii  libc6         2.13-27
ii  libgcc1       1:4.6.2-16
ii  libice6       2:1.0.7-2
ii  libsm6        2:1.2.0-2
ii  libstdc++6    4.6.2-16
ii  libx11-6      2:1.4.4-4
ii  libxext6      2:1.3.0-3
ii  libxi6        2:1.4.5-1
ii  libxinerama1  2:1.1.1-3
ii  libxtst6      2:1.2.0-4

synergy recommends no packages.

synergy suggests no packages.

-- no debconf information

**Comment by epakai** [comment]
BTS_msg_id: <1332179667-sup-3557@pimlott.net>
BTS author: Andrew Pimlott <andrew@pimlott.net>

I can still reproduce the problem using synergyc from the same package
version, 1.3.8-1.

Andrew

**Comment by epakai** [comment]
BTS_msg_id: <5002FD8F.6040001@debian.org>
BTS author: Jeff Licquia <licquia@debian.org>

I've uploaded 1.3.8-2, with a segfault fix that seems to have fixed a
number of reported problems (both in and out of Debian).  Can you test
with that version, and let me know if you still see the problem?
